# Generated by Django 6.0.7 on 2026-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/profile_pics.png', upload_to='profile_pics'),
        ),
    ]
