# Generated by Django 6.0.7 on 2026-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUqjfF2N_HwBrk8VhXDoFti-LGbBjoPi9cMaORPpFx4A&s=10', max_length=500),
        ),
    ]
