# Generated by Django 6.0.7 on 2026-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
