# Generated by Django 6.0.7 on 2026-09-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_item_is_deleted_alter_item_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
